global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flaskapp'
    static_configs:
      - targets: ['app:8082']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

